# Makefile

CC := g++
CFLAGS := -Wall
TARGET := best_factorial.cpp
BUILD := factorial

all: .PHONY

factorial:
	${CC} ${TARGET} ${CFLAGS} -o ${BUILD}

clean:
	rm -rf a.out ${BUILD}

.PHONY: factorial
